services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: email-system-backend
    ports:
      - "8000:8000"
    volumes:
      - ./token.json:/app/token.json
      - ./credentials.json:/app/credentials.json
    env_file:
      - .env
    restart: on-failure

  frontend:
    build:
      context: ./face
      dockerfile: Dockerfile.frontend
    container_name: email-system-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: on-failure
